### ISSUE TITLE
RxSwift needs updated

### ISSUE THREAD

**Issue by allygreen** [intuit/CardParts#239]
**Describe the bug**
When submitting app's using cardparts to the app store, apple sends an email with this content.
 
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

This is due to the RxSwift version being kept at 4.5. 

The RxSwift maintainers have just bumped the version to 5.1 to remove any usage or reference with the UIWebView API's. 

https://github.com/ReactiveX/RxSwift/issues/2055

Is it possible for CardParts to bump it's RxSwift to version 5.1?

**Comment by MatrixSenpai** [comment]
I'm adding my +1 to this, with some additional comments.

First off, I understand the decision to keep RxSwift/RxCocoa at v4 for such a long time (see #64) but that was a year ago, and I think that it's time to move on. I've been unable to include CardParts in my work for a long time because of this, and I've desperately wanted to use this library. Old versions can still be used, hell, even an opening a new branch with a version using Rx v4 and updating it from time to time would be better than this

**Comment by croossin** [comment]
This has been fixed and released in [version 3.0.0](https://github.com/intuit/CardParts/releases/tag/3.0.0)
